version: '2'
services:
  circled-server:
    image: gubble/circled-server:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SQLITE_FILE: "/mnt/data1/circled.db"
      BIND_ADDRESS: "0.0.0.0:8080"
    volumes:
      - ./circled-data:/mnt/data1