version: '2'
services:
  circled-server:
    image: gubble/circled-server:latest
    # build:
    #  dockerfile: Dockerfile
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      MYSQL_DSN: "root:@tcp(mysql:3306)/circled?charset=utf8mb4&parseTime=True&loc=Local"
      BIND_ADDRESS: 0.0.0.0:8080
    volumes:
      - ./asset-data:/mnt/data1

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: circled
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: mysqladmin ping --silent
      start_period: 5s
      interval: 3s
      timeout: 5s
      retries: 20