name: Docker Image CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag gubble/circled-server:$TAG
      env:
        TAG: ${{github.ref_name}}
