package models

type Face struct {
	ID        uint64  `gorm:"primaryKey"` // not really needed, but GORM cannot have a foreign key to a composite primary key, so here it is
	CreatedAt int64   `gorm:""`
	AssetID   uint64  `gorm:"index:uniq_asset_face,unique;priority:1"`
	Asset     Asset   `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
	Num       int     `gorm:"index:uniq_asset_face,unique;"`
	Top       int     `gorm:"type:int"`
	Right     int     `gorm:"type:int"`
	Bottom    int     `gorm:"type:int"`
	Left      int     `gorm:"type:int"`
	V0        float64 `gorm:"type:double"`
	V1        float64 `gorm:"type:double"`
	V2        float64 `gorm:"type:double"`
	V3        float64 `gorm:"type:double"`
	V4        float64 `gorm:"type:double"`
	V5        float64 `gorm:"type:double"`
	V6        float64 `gorm:"type:double"`
	V7        float64 `gorm:"type:double"`
	V8        float64 `gorm:"type:double"`
	V9        float64 `gorm:"type:double"`
	V10       float64 `gorm:"type:double"`
	V11       float64 `gorm:"type:double"`
	V12       float64 `gorm:"type:double"`
	V13       float64 `gorm:"type:double"`
	V14       float64 `gorm:"type:double"`
	V15       float64 `gorm:"type:double"`
	V16       float64 `gorm:"type:double"`
	V17       float64 `gorm:"type:double"`
	V18       float64 `gorm:"type:double"`
	V19       float64 `gorm:"type:double"`
	V20       float64 `gorm:"type:double"`
	V21       float64 `gorm:"type:double"`
	V22       float64 `gorm:"type:double"`
	V23       float64 `gorm:"type:double"`
	V24       float64 `gorm:"type:double"`
	V25       float64 `gorm:"type:double"`
	V26       float64 `gorm:"type:double"`
	V27       float64 `gorm:"type:double"`
	V28       float64 `gorm:"type:double"`
	V29       float64 `gorm:"type:double"`
	V30       float64 `gorm:"type:double"`
	V31       float64 `gorm:"type:double"`
	V32       float64 `gorm:"type:double"`
	V33       float64 `gorm:"type:double"`
	V34       float64 `gorm:"type:double"`
	V35       float64 `gorm:"type:double"`
	V36       float64 `gorm:"type:double"`
	V37       float64 `gorm:"type:double"`
	V38       float64 `gorm:"type:double"`
	V39       float64 `gorm:"type:double"`
	V40       float64 `gorm:"type:double"`
	V41       float64 `gorm:"type:double"`
	V42       float64 `gorm:"type:double"`
	V43       float64 `gorm:"type:double"`
	V44       float64 `gorm:"type:double"`
	V45       float64 `gorm:"type:double"`
	V46       float64 `gorm:"type:double"`
	V47       float64 `gorm:"type:double"`
	V48       float64 `gorm:"type:double"`
	V49       float64 `gorm:"type:double"`
	V50       float64 `gorm:"type:double"`
	V51       float64 `gorm:"type:double"`
	V52       float64 `gorm:"type:double"`
	V53       float64 `gorm:"type:double"`
	V54       float64 `gorm:"type:double"`
	V55       float64 `gorm:"type:double"`
	V56       float64 `gorm:"type:double"`
	V57       float64 `gorm:"type:double"`
	V58       float64 `gorm:"type:double"`
	V59       float64 `gorm:"type:double"`
	V60       float64 `gorm:"type:double"`
	V61       float64 `gorm:"type:double"`
	V62       float64 `gorm:"type:double"`
	V63       float64 `gorm:"type:double"`
	V64       float64 `gorm:"type:double"`
	V65       float64 `gorm:"type:double"`
	V66       float64 `gorm:"type:double"`
	V67       float64 `gorm:"type:double"`
	V68       float64 `gorm:"type:double"`
	V69       float64 `gorm:"type:double"`
	V70       float64 `gorm:"type:double"`
	V71       float64 `gorm:"type:double"`
	V72       float64 `gorm:"type:double"`
	V73       float64 `gorm:"type:double"`
	V74       float64 `gorm:"type:double"`
	V75       float64 `gorm:"type:double"`
	V76       float64 `gorm:"type:double"`
	V77       float64 `gorm:"type:double"`
	V78       float64 `gorm:"type:double"`
	V79       float64 `gorm:"type:double"`
	V80       float64 `gorm:"type:double"`
	V81       float64 `gorm:"type:double"`
	V82       float64 `gorm:"type:double"`
	V83       float64 `gorm:"type:double"`
	V84       float64 `gorm:"type:double"`
	V85       float64 `gorm:"type:double"`
	V86       float64 `gorm:"type:double"`
	V87       float64 `gorm:"type:double"`
	V88       float64 `gorm:"type:double"`
	V89       float64 `gorm:"type:double"`
	V90       float64 `gorm:"type:double"`
	V91       float64 `gorm:"type:double"`
	V92       float64 `gorm:"type:double"`
	V93       float64 `gorm:"type:double"`
	V94       float64 `gorm:"type:double"`
	V95       float64 `gorm:"type:double"`
	V96       float64 `gorm:"type:double"`
	V97       float64 `gorm:"type:double"`
	V98       float64 `gorm:"type:double"`
	V99       float64 `gorm:"type:double"`
	V100      float64 `gorm:"type:double"`
	V101      float64 `gorm:"type:double"`
	V102      float64 `gorm:"type:double"`
	V103      float64 `gorm:"type:double"`
	V104      float64 `gorm:"type:double"`
	V105      float64 `gorm:"type:double"`
	V106      float64 `gorm:"type:double"`
	V107      float64 `gorm:"type:double"`
	V108      float64 `gorm:"type:double"`
	V109      float64 `gorm:"type:double"`
	V110      float64 `gorm:"type:double"`
	V111      float64 `gorm:"type:double"`
	V112      float64 `gorm:"type:double"`
	V113      float64 `gorm:"type:double"`
	V114      float64 `gorm:"type:double"`
	V115      float64 `gorm:"type:double"`
	V116      float64 `gorm:"type:double"`
	V117      float64 `gorm:"type:double"`
	V118      float64 `gorm:"type:double"`
	V119      float64 `gorm:"type:double"`
	V120      float64 `gorm:"type:double"`
	V121      float64 `gorm:"type:double"`
	V122      float64 `gorm:"type:double"`
	V123      float64 `gorm:"type:double"`
	V124      float64 `gorm:"type:double"`
	V125      float64 `gorm:"type:double"`
	V126      float64 `gorm:"type:double"`
	V127      float64 `gorm:"type:double"`
}
