package models

type Face struct {
	ID        uint64  `gorm:"primaryKey"`
	CreatedAt int64   `gorm:""`
	AssetID   uint64  `gorm:"index:uniq_asset_face,unique;priority:1"`
	Asset     Asset   `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
	PersonID  *uint64 `gorm:""`
	Person    Person  `gorm:"constraint:OnUpdate:CASCADE,OnDelete:SET NULL;"`
	Num       int     `gorm:"index:uniq_asset_face,unique;"`
	X1        int     `gorm:"type:int"`
	Y1        int     `gorm:"type:int"`
	X2        int     `gorm:"type:int"`
	Y2        int     `gorm:"type:int"`
	V0        float32 `gorm:"type:double"`
	V1        float32 `gorm:"type:double"`
	V2        float32 `gorm:"type:double"`
	V3        float32 `gorm:"type:double"`
	V4        float32 `gorm:"type:double"`
	V5        float32 `gorm:"type:double"`
	V6        float32 `gorm:"type:double"`
	V7        float32 `gorm:"type:double"`
	V8        float32 `gorm:"type:double"`
	V9        float32 `gorm:"type:double"`
	V10       float32 `gorm:"type:double"`
	V11       float32 `gorm:"type:double"`
	V12       float32 `gorm:"type:double"`
	V13       float32 `gorm:"type:double"`
	V14       float32 `gorm:"type:double"`
	V15       float32 `gorm:"type:double"`
	V16       float32 `gorm:"type:double"`
	V17       float32 `gorm:"type:double"`
	V18       float32 `gorm:"type:double"`
	V19       float32 `gorm:"type:double"`
	V20       float32 `gorm:"type:double"`
	V21       float32 `gorm:"type:double"`
	V22       float32 `gorm:"type:double"`
	V23       float32 `gorm:"type:double"`
	V24       float32 `gorm:"type:double"`
	V25       float32 `gorm:"type:double"`
	V26       float32 `gorm:"type:double"`
	V27       float32 `gorm:"type:double"`
	V28       float32 `gorm:"type:double"`
	V29       float32 `gorm:"type:double"`
	V30       float32 `gorm:"type:double"`
	V31       float32 `gorm:"type:double"`
	V32       float32 `gorm:"type:double"`
	V33       float32 `gorm:"type:double"`
	V34       float32 `gorm:"type:double"`
	V35       float32 `gorm:"type:double"`
	V36       float32 `gorm:"type:double"`
	V37       float32 `gorm:"type:double"`
	V38       float32 `gorm:"type:double"`
	V39       float32 `gorm:"type:double"`
	V40       float32 `gorm:"type:double"`
	V41       float32 `gorm:"type:double"`
	V42       float32 `gorm:"type:double"`
	V43       float32 `gorm:"type:double"`
	V44       float32 `gorm:"type:double"`
	V45       float32 `gorm:"type:double"`
	V46       float32 `gorm:"type:double"`
	V47       float32 `gorm:"type:double"`
	V48       float32 `gorm:"type:double"`
	V49       float32 `gorm:"type:double"`
	V50       float32 `gorm:"type:double"`
	V51       float32 `gorm:"type:double"`
	V52       float32 `gorm:"type:double"`
	V53       float32 `gorm:"type:double"`
	V54       float32 `gorm:"type:double"`
	V55       float32 `gorm:"type:double"`
	V56       float32 `gorm:"type:double"`
	V57       float32 `gorm:"type:double"`
	V58       float32 `gorm:"type:double"`
	V59       float32 `gorm:"type:double"`
	V60       float32 `gorm:"type:double"`
	V61       float32 `gorm:"type:double"`
	V62       float32 `gorm:"type:double"`
	V63       float32 `gorm:"type:double"`
	V64       float32 `gorm:"type:double"`
	V65       float32 `gorm:"type:double"`
	V66       float32 `gorm:"type:double"`
	V67       float32 `gorm:"type:double"`
	V68       float32 `gorm:"type:double"`
	V69       float32 `gorm:"type:double"`
	V70       float32 `gorm:"type:double"`
	V71       float32 `gorm:"type:double"`
	V72       float32 `gorm:"type:double"`
	V73       float32 `gorm:"type:double"`
	V74       float32 `gorm:"type:double"`
	V75       float32 `gorm:"type:double"`
	V76       float32 `gorm:"type:double"`
	V77       float32 `gorm:"type:double"`
	V78       float32 `gorm:"type:double"`
	V79       float32 `gorm:"type:double"`
	V80       float32 `gorm:"type:double"`
	V81       float32 `gorm:"type:double"`
	V82       float32 `gorm:"type:double"`
	V83       float32 `gorm:"type:double"`
	V84       float32 `gorm:"type:double"`
	V85       float32 `gorm:"type:double"`
	V86       float32 `gorm:"type:double"`
	V87       float32 `gorm:"type:double"`
	V88       float32 `gorm:"type:double"`
	V89       float32 `gorm:"type:double"`
	V90       float32 `gorm:"type:double"`
	V91       float32 `gorm:"type:double"`
	V92       float32 `gorm:"type:double"`
	V93       float32 `gorm:"type:double"`
	V94       float32 `gorm:"type:double"`
	V95       float32 `gorm:"type:double"`
	V96       float32 `gorm:"type:double"`
	V97       float32 `gorm:"type:double"`
	V98       float32 `gorm:"type:double"`
	V99       float32 `gorm:"type:double"`
	V100      float32 `gorm:"type:double"`
	V101      float32 `gorm:"type:double"`
	V102      float32 `gorm:"type:double"`
	V103      float32 `gorm:"type:double"`
	V104      float32 `gorm:"type:double"`
	V105      float32 `gorm:"type:double"`
	V106      float32 `gorm:"type:double"`
	V107      float32 `gorm:"type:double"`
	V108      float32 `gorm:"type:double"`
	V109      float32 `gorm:"type:double"`
	V110      float32 `gorm:"type:double"`
	V111      float32 `gorm:"type:double"`
	V112      float32 `gorm:"type:double"`
	V113      float32 `gorm:"type:double"`
	V114      float32 `gorm:"type:double"`
	V115      float32 `gorm:"type:double"`
	V116      float32 `gorm:"type:double"`
	V117      float32 `gorm:"type:double"`
	V118      float32 `gorm:"type:double"`
	V119      float32 `gorm:"type:double"`
	V120      float32 `gorm:"type:double"`
	V121      float32 `gorm:"type:double"`
	V122      float32 `gorm:"type:double"`
	V123      float32 `gorm:"type:double"`
	V124      float32 `gorm:"type:double"`
	V125      float32 `gorm:"type:double"`
	V126      float32 `gorm:"type:double"`
	V127      float32 `gorm:"type:double"`
}
